language: java
sudo: false

matrix:
  include:
    # Ubuntu Linux (trusty) / Open DK 11 / Headed (AWT Robot)
    - os: linux
      dist: trusty
      jdk: openjdk11
      env:
        - _JAVA_OPTIONS="-Dtestfx.robot=awt"
    # Ubuntu Linux (trusty) / Open DK 11 / Headed (Glass Robot) / HiDPI
    - os: linux
      dist: trusty
      jdk: openjdk11
      env:
        - _JAVA_OPTIONS="-Dtestfx.robot=glass -Dglass.gtk.uiScale=2.0"
    # Ubuntu Linux (trusty) / Open DK 11 / Headless
    - os: linux
      dist: trusty
      jdk: openjdk11
      env:
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw"
    # macOS / JDK11 / Headless
    - os: osx
      osx_image: xcode10.1
      jdk: oraclejdk11
      env:
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.verbose=true"
    # Headed macOS is not currently possible on Travis.
    
before_install:
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then 
      export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; 
    elif [[ "${TRAVIS_OS_NAME}" == osx ]]; then
      brew update && brew install gettext && brew link --force gettext;
    fi

