version: '{build}'
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile('https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.3.9/apache-maven-3.3.9-bin.zip', 'C:\maven-bin.zip')
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
      if (!(Test-Path -Path "C:\gettext" )) {
        (new-object System.Net.WebClient).DownloadFile('https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.19.8.1-v1.14/gettext0.19.8.1-iconv1.14-shared-64.zip', 'C:\gettext-bin.zip')
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\gettext-bin.zip", "C:\gettext")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.3.9\bin;%JAVA_HOME%\bin;C:\gettext\bin;
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean package -B -DskipTests
test_script:
  - mvn clean install
cache:
- C:\maven\
- C:\Users\appveyor\.m2